image:
  file: .gitpod.Dockerfile
tasks:
  - init: /opt/solr-8.8.2/bin/solr start && /opt/solr-8.8.2/bin/solr create -c films -s 2 -rf 2 &&  /opt/solr-8.8.2/bin/post -c films /opt/solr-8.8.2/example/films/films.xml
ports:
  - port: 8983
    onOpen: open-browser
  - port: 3000
    onOpen: open-browser
