tasks:
  - init: cd /workspace && git clone https://github.com/grafana/grafana && 
          wget https://ftp.itu.edu.tr/Mirror/Apache/lucene/solr/8.8.1/solr-8.8.1.tgz && tar -xvzf ./solr-8.8.1.tgz && 
    command: /workspace/solr-8.8.1/bin/solr start && cd grafana && yarn install --pure-lockfile --no-progress 

ports:
  - port: 8983
    onOpen: open-browser
  - port: 3000
    onOpen: open-browser
